baseURL = "https://westwoodlabs.github.io/ruegenmanifest"
languageCode = "de-de"
title = "Das Rügenmanifest"
theme="archie"
copyright = "Westwoodlabs e.V."

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/westwoodlabs/ruegenmanifest"
